CREATE TABLE IF NOT EXISTS usuarios (
    id TEXT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    provider VARCHAR(50), 
    imagem_url VARCHAR(250),
    config JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);
